server:
  port: 10014
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
spring:
  application:
    name: spring-ai
  ai:
    #    DashScopeConnectionProperties
    dashscope:
      index-name: test_knowledge
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3.6-plus
      agent:
        app-id: 0f8e9da11e24477a93fe5d0e12218881
        mcp:
          server:
            name: streamable-mcp-server2
            protocol: streamable # SSE、STREAMABLE、STATELESS
            version: 1.0.0
            type: ASYNC  # Recommended for reactive applications
            instructions: "This reactive server provides time information tools and resources"
            capabilities:
              tool: true
              resource: true
              prompt: true
              completion: true
            request-timeout: 20s
            streamable-http:
              mcp-endpoint: /mcp
              keep-alive-interval: 30s
              disallow-delete: false

    memory:
      MAX_MEMORY_SIZE: 1000
      CONVERSATION_ID: chat_memory_conversation_id
#      repository:
#        jdbc:
#          mysql:
#            jdbc-url: jdbc:mysql://localhost:3306/spring_ai_alibaba_mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
#            username: root
#            password: root
#            driver-class-name: com.mysql.cj.jdbc.Driver
#            enabled: true

